from collections.abc import Sequence
from typing import TypeAlias

PredicateSpec: TypeAlias = tuple[str, str, list[str]]
ErrorFields: TypeAlias = tuple[
    str,
    str,
    str | None,
    int | None,
    int | None,
    int | None,
    int | None,
]
DiagnosticFields: TypeAlias = tuple[str, str, str, list[str]]
ValidationFields: TypeAlias = tuple[
    str,
    str,
    list[str],
    list[DiagnosticFields],
]

class _CifDocument:
    @property
    def block_count(self) -> int: ...
    def to_canonical(self) -> str: ...
    def to_preserving(self) -> str: ...
    def to_binary(self) -> bytes: ...

class _CifTable:
    @property
    def category(self) -> str: ...
    @property
    def columns(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def _with_missing(self, missing: str) -> _CifTable: ...
    def __arrow_c_stream__(self, requested_schema: object = None) -> object: ...

class _PdbxModel:
    @property
    def entry_id(self) -> str: ...
    @property
    def entity_count(self) -> int: ...
    @property
    def asym_unit_count(self) -> int: ...
    @property
    def component_count(self) -> int: ...
    @property
    def atom_site_count(self) -> int: ...
    @property
    def connection_count(self) -> int: ...
    @property
    def entity_kinds(self) -> list[str]: ...
    @property
    def component_ids(self) -> list[str]: ...
    def to_document(self) -> _CifDocument: ...
    def source_document(self) -> _CifDocument: ...

class _ModelCifModel:
    @property
    def entry_id(self) -> str: ...
    @property
    def entity_count(self) -> int: ...
    @property
    def asym_unit_count(self) -> int: ...
    @property
    def component_count(self) -> int: ...
    @property
    def atom_site_count(self) -> int: ...
    @property
    def connection_count(self) -> int: ...
    @property
    def entity_kinds(self) -> list[str]: ...
    @property
    def component_ids(self) -> list[str]: ...
    @property
    def prediction_model_count(self) -> int: ...
    @property
    def target_entity_count(self) -> int: ...
    @property
    def template_count(self) -> int: ...
    @property
    def qa_metric_count(self) -> int: ...
    @property
    def qa_value_count(self) -> int: ...
    @property
    def software_names(self) -> list[str]: ...
    @property
    def qa_metric_names(self) -> list[str]: ...
    @property
    def qa_metric_modes(self) -> list[str]: ...
    def to_document(
        self, mirror_local_qa_metric: int | None = None
    ) -> _CifDocument: ...
    def source_document(self) -> _CifDocument: ...

class _ComponentRegistry:
    def __len__(self) -> int: ...

class _NativeScan:
    def __init__(
        self,
        workers: int,
        category: str | None = None,
        columns: Sequence[str] | None = None,
        predicates: Sequence[PredicateSpec] = (),
        schema: str | None = None,
    ) -> None: ...
    def submit_file(self, file: str) -> int: ...
    def submit_bytes(self, source_name: str, bytes: bytes) -> int: ...
    def next(
        self,
    ) -> tuple[int, _CifDocument | _CifTable | None, ErrorFields | None] | None: ...
    def close(self) -> None: ...
    def cancel(self) -> None: ...

def native_version() -> str: ...
def contract_version() -> int: ...
def build_profile() -> str: ...
def read_file(
    file: str,
    category: str | None = None,
    columns: Sequence[str] | None = None,
    predicates: Sequence[PredicateSpec] = (),
    schema: str | None = None,
) -> _CifDocument | _CifTable: ...
def read_bytes(
    source_name: str,
    bytes: bytes,
    category: str | None = None,
    columns: Sequence[str] | None = None,
    predicates: Sequence[PredicateSpec] = (),
    schema: str | None = None,
) -> _CifDocument | _CifTable: ...
def validate_document(
    document: _CifDocument,
    schema: str,
) -> ValidationFields: ...
def build_pdbx_model(
    document: _CifDocument,
    registry: _ComponentRegistry | None = None,
) -> _PdbxModel: ...
def build_modelcif_model(
    document: _CifDocument,
    registry: _ComponentRegistry | None = None,
) -> _ModelCifModel: ...
def build_component_registry(document: _CifDocument) -> _ComponentRegistry: ...
def validate_pdbx_document(document: _CifDocument) -> ValidationFields: ...
def validate_pdbx_model(model: _PdbxModel) -> ValidationFields: ...
def validate_modelcif_document(document: _CifDocument) -> ValidationFields: ...
def validate_modelcif_model(model: _ModelCifModel) -> ValidationFields: ...
