from collections.abc import Sequence
from typing import Literal, TypeAlias

PredicateSpec: TypeAlias = tuple[str, str, list[str]]
ErrorFields: TypeAlias = tuple[
    str,
    str,
    str | None,
    int | None,
    int | None,
    int | None,
    int | None,
]
DiagnosticFields: TypeAlias = tuple[str, str, str, list[str]]
ValidationFields: TypeAlias = tuple[
    str,
    str,
    list[str],
    list[DiagnosticFields],
]

class CifDocument:
    @property
    def block_count(self) -> int: ...
    @property
    def schema(self) -> str | None: ...
    def to_canonical(self) -> str: ...
    def to_preserving(self) -> str: ...
    def to_binary(self) -> bytes: ...

class CifTable:
    @property
    def category(self) -> str: ...
    @property
    def columns(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def with_missing(
        self, missing: Literal["collapse", "columns", "extension"]
    ) -> CifTable: ...
    def __arrow_c_stream__(self, requested_schema: object = None) -> object: ...

class MmcifModel:
    @property
    def profile(self) -> Literal["pdbx", "modelcif"]: ...
    @property
    def entry_id(self) -> str: ...
    @property
    def entity_count(self) -> int: ...
    @property
    def asym_unit_count(self) -> int: ...
    @property
    def component_count(self) -> int: ...
    @property
    def atom_site_count(self) -> int: ...
    @property
    def connection_count(self) -> int: ...
    @property
    def entity_kinds(self) -> list[str]: ...
    @property
    def component_ids(self) -> list[str]: ...
    @property
    def prediction_model_count(self) -> int: ...
    @property
    def target_entity_count(self) -> int: ...
    @property
    def template_count(self) -> int: ...
    @property
    def qa_metric_count(self) -> int: ...
    @property
    def qa_value_count(self) -> int: ...
    @property
    def software_names(self) -> list[str]: ...
    @property
    def qa_metric_names(self) -> list[str]: ...
    @property
    def qa_metric_modes(self) -> list[str]: ...
    def source_document(self) -> CifDocument: ...

class Registry:
    def __len__(self) -> int: ...

class _NativeScan:
    def __init__(
        self,
        workers: int,
        category: str | None = None,
        columns: Sequence[str] | None = None,
        predicates: Sequence[PredicateSpec] = (),
        schema: str | None = None,
    ) -> None: ...
    def submit_file(self, file: str) -> None: ...
    def submit_bytes(self, source_name: str, bytes: bytes) -> None: ...
    def next(
        self,
    ) -> tuple[int, CifDocument | CifTable | None, ErrorFields | None] | None: ...
    def close(self) -> None: ...
    def cancel(self) -> None: ...

def native_version() -> str: ...
def contract_version() -> int: ...
def build_profile() -> str: ...
def read_file(
    file: str,
    category: str | None = None,
    columns: Sequence[str] | None = None,
    predicates: Sequence[PredicateSpec] = (),
    schema: str | None = None,
) -> CifDocument | CifTable: ...
def read_bytes(
    source_name: str,
    bytes: bytes,
    category: str | None = None,
    columns: Sequence[str] | None = None,
    predicates: Sequence[PredicateSpec] = (),
    schema: str | None = None,
) -> CifDocument | CifTable: ...
def validate_document(
    document: CifDocument,
    schema: str,
) -> ValidationFields: ...
def build_mmcif_model(
    document: CifDocument,
    profile: Literal["pdbx", "modelcif"],
    registry: Registry | None = None,
) -> MmcifModel: ...
def _model_document(
    model: MmcifModel, mirror_local_qa_metric: int | None = None
) -> CifDocument: ...
def build_component_registry(document: CifDocument) -> Registry: ...
def validate_mmcif_document(
    document: CifDocument, profile: Literal["pdbx", "modelcif"]
) -> ValidationFields: ...
def validate_mmcif_model(model: MmcifModel) -> ValidationFields: ...
