format_version = 1
artifact_format_version = 1

[[schema]]
name = "pdbx"
dictionary_name = "mmcif_pdbx.dic"
version = "5.416"
file = "mmcif_pdbx_v50.dic"
url = "https://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic"
sha256 = "78c038f20f69601b86f128c0d543576f4284da67c36284c344669da0f4f5e27a"
retrieved_on = "2026-08-11"
artifact = "pdbx.nbs"
extensions = []

[[schema]]
name = "modelcif"
dictionary_name = "mmcif_ma.dic"
version = "1.4.9"
file = "mmcif_ma.dic"
url = "https://mmcif.wwpdb.org/dictionaries/ascii/mmcif_ma.dic"
sha256 = "aeb205bbf23d459089c694eec004978c78497e5f5d3dd5642120dd0d62e9b844"
retrieved_on = "2026-08-11"
artifact = "modelcif.nbs"
extensions = ["pdbx"]
